Repository pycontribs/ansi2html, pull requests merged in 2020-10, with the labels that each got.

#112 Refactor packaging and officialy retire support for python <= 3.6
  README.rst
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: major

#103 Remove nose
  tests/test_ansi2html.py
  tox.ini
Labels: test

#113 Enable release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#106 Add dracula colorscheme
  ansi2html/style.py
Labels: feature

#114 Fixed FutureWarning
  ansi2html/converter.py
  tox.ini
Labels: bug

#115 Remove use of six library
  ansi2html/converter.py
  setup.cfg
  tests/test_ansi2html.py
Labels: deprecated

#116 Enable pre-commit
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  ansi2html/converter.py
  tests/ansicolor_eix.html
  tests/ansicolor_eix.txt
  tests/test_ansi2html.py
  tox.ini
Labels: enhancement

#117 Enabled black
  .pre-commit-config.yaml
  ansi2html/__init__.py
  ansi2html/converter.py
  ansi2html/style.py
  ansi2html/util.py
  tests/test_ansi2html.py
Labels: test

#118 Enable isort
  .pre-commit-config.yaml
  ansi2html/converter.py
  pyproject.toml
  tests/test_ansi2html.py
Labels: enhancement

#119 Enable flake8 and pylint
  .pre-commit-config.yaml
  .pylintrc
  ansi2html/converter.py
  ansi2html/style.py
  setup.cfg
  tests/test_ansi2html.py
Labels: test

#120 Assure ansi2html can be called as script or module
  ansi2html/__main__.py
  setup.cfg
  tests/test_ansi2html.py
Labels: bug

#121 Merge from develop to master
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .pylintrc
  .travis.yml
  README.rst
  ansi2html/__init__.py
  ansi2html/__main__.py
  ansi2html/converter.py
  ansi2html/style.py
  ansi2html/util.py
  pyproject.toml
  setup.cfg
  setup.py
  tests/ansicolor_eix.html
  tests/ansicolor_eix.txt
  tests/produce_headers.txt
  tests/test_ansi2html.py
  tox.ini
Labels: skip-changelog

#122 Correct author metadata
  setup.cfg
Labels: bug
