Repository pycontribs/ansi2html, pull requests merged in 2021-09, with the labels that each got.

#129 Replace recommendation of using system packages with pip3
  README.rst
Labels: docs

#137 Bump linters
  .pre-commit-config.yaml
  ansi2html/converter.py
  tests/test_ansi2html.py
Labels: skip-changelog

#138 Bump setuptools-scm version
  pyproject.toml
  setup.cfg
  setup.py
Labels: bug

#136 Create CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#139 Refresh release pipelines
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#125 Start using pytest to run the tests
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#131 Adds support for OSC hyperlink sequences.
  ansi2html/converter.py
  tests/test_ansi2html.py
Labels: feature

#141 Sphinx docs
  README.rst
  ansi2html/converter.py
  docs/Makefile
  docs/make.bat
  docs/source/api.rst
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/index.rst
  readthedocs.yml
  setup.cfg
  tox.ini
Labels: docs, enhancement
