Repository pycontribs/ansi2html, pull requests merged in 2023-12, with the labels that each got.

#221 Fix tox and readthedocs
  .github/workflows/tox.yml
  readthedocs.yml
  tox.ini
Labels: skip-changelog

#228 Fix RTD builds
  .gitignore
  .readthedocs.yml
  readthedocs.yml
  tox.ini
Labels: bug

#229 Fix project description
  pyproject.toml
Labels: bug

#230 Enable testing with py312
  .github/workflows/tox.yml
  pyproject.toml
Labels: minor

#232 Fix release pipeline
  .github/workflows/release.yml
Labels: skip-changelog
