Repository pycontribs/ansi2html, pull requests merged in 2023-01, with the labels that each got.

#194 Build/test refactoring
  .config/requirements.txt
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/labels.yml
  .github/workflows/push.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .gitignore
  tox.ini
Labels: bug

#192 Fix license headers in source files
  ansi2html/converter.py
  ansi2html/style.py
  tests/test_ansi2html.py
Labels: bug

#195 Test with py36 and py37
  .github/workflows/tox.yml
Labels: bug

#196 Move tool config to pyproject.toml
  .pylintrc
  mypy.ini
  pyproject.toml
Labels: bug, skip-changelog

#197 Enable prettier
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  ansi2html/style.py
  pyproject.toml
Labels: bug

#198 Adopt PEP-621
  .flake8
  .gitignore
  MANIFEST.in
  ansi2html/__init__.py
  docs/source/conf.py
  pyproject.toml
  setup.cfg
  src/ansi2html/__init__.py
  src/ansi2html/__main__.py
  src/ansi2html/converter.py
  src/ansi2html/py.typed
  src/ansi2html/style.py
  src/ansi2html/util.py
Labels: enhancement

#199 Ensure we require py37 or newer
  pyproject.toml
Labels: bug

#200 Add funding badge
  .github/FUNDING.yml
Labels: skip-changelog

#204 Replace sphinx with mkdocs
  .gitignore
  CHANGELOG.rst
  README.md
  README.rst
  docs/Makefile
  docs/api.md
  docs/changelog.md
  docs/index.md
  docs/make.bat
  docs/source/api.rst
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/index.rst
  mkdocs.yml
  pyproject.toml
  readthedocs.yml
  tox.ini
Labels: bug

#205 Replace optparse with argparse
  src/ansi2html/converter.py
Labels: bug
